"""
Plot frame-level importance score curves for video summarization results.

Reads consolidated per-video data from figure/data/{summe,tvsum}/*.json
(generated by build_figure_data.py).

Usage:
    python figure/plot_score_curves.py                     # top-5 per dataset
    python figure/plot_score_curves.py --top 3             # top-3 per dataset
    python figure/plot_score_curves.py --video summe:Air_Force_One  # single video
"""
import argparse
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator
import numpy as np

# ── paths ────────────────────────────────────────────────────────────────
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE, "figure", "data")
OUT_DIR = os.path.join(BASE, "figure")
os.makedirs(OUT_DIR, exist_ok=True)


# ── data loading (from consolidated JSONs) ───────────────────────────────
def load_rankings():
    with open(os.path.join(DATA_DIR, "rankings.json"), encoding="utf-8") as f:
        return json.load(f)


def load_video_data(dataset: str, video_name: str):
    """Load consolidated per-video JSON from figure/data/{dataset}/{video}.json"""
    path = os.path.join(DATA_DIR, dataset, f"{video_name}.json")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


# ── plotting ─────────────────────────────────────────────────────────────
# Global style -----------------------------------------------------------
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 9,
    "axes.labelsize": 10,
    "axes.titlesize": 10,
    "legend.fontsize": 8,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.05,
})

# colour palette (colour-blind friendly)
C_LLM   = "#2166AC"   # blue
C_FS    = "#4DAC26"   # green
C_FV    = "#D6604D"   # red
C_FINAL = "#1B1B1B"   # near-black
C_GT    = "#BFBFBF"   # light grey for GT background


def plot_video(dataset: str, video_name: str, out_path: str, rank_info=None):
    """Plot 4-subplot score curves with GT background for one video."""
    vdata = load_video_data(dataset, video_name)

    picks = np.asarray(vdata["picks"])
    s_llm = np.asarray(vdata["scores"]["s_llm"])
    s_fs  = np.asarray(vdata["scores"]["s_fs"])
    s_fv  = np.asarray(vdata["scores"]["s_fv"])
    final = np.asarray(vdata["scores"]["final"])
    gt    = np.asarray(vdata["gt_score"])

    # time axis: frame indices → seconds (sampled at ~15 fps)
    t = picks / 15.0
    t_gt = np.arange(len(gt)) * (t[-1] / (len(gt) - 1)) if len(gt) > 1 else t

    fig, axes = plt.subplots(
        4, 1, figsize=(7.0, 5.0), sharex=True,
        gridspec_kw={"hspace": 0.12}
    )

    def _draw(ax, y, colour, label):
        ax.fill_between(t_gt, 0, gt, color=C_GT, alpha=0.45, label="GT")
        ax.plot(t, y, color=colour, linewidth=0.9, label=label)
        ax.fill_between(t, 0, y, color=colour, alpha=0.12)
        ax.set_ylabel(label, fontsize=9)
        ax.set_ylim(bottom=0)
        ax.yaxis.set_minor_locator(AutoMinorLocator())
        ax.grid(axis="y", linewidth=0.3, alpha=0.5)
        ax.tick_params(direction="in", which="both")

    _draw(axes[0], s_llm,  C_LLM,  r"$S_{\mathrm{LLM}}$")
    _draw(axes[1], s_fs,   C_FS,   r"$S_{FS}$")
    _draw(axes[2], s_fv,   C_FV,   r"$S_{FV}$")
    _draw(axes[3], final,  C_FINAL, r"$F(p_j)$")

    axes[-1].set_xlabel("Time (s)")
    axes[-1].legend(loc="upper right", framealpha=0.8, fontsize=7)

    # title: dataset — video name (F1=xx)
    ds_label = "SumMe" if dataset == "summe" else "TVSum"
    f1_val = (rank_info or {}).get("f1") or vdata.get("evaluation", {}).get("f1")
    title = f"{ds_label}  —  {video_name.replace('_', ' ')}"
    if f1_val is not None:
        title += f"  (F1={f1_val:.4f})"
    fig.suptitle(title, fontsize=11, fontweight="bold", y=0.98)

    # metric annotation bar (curve-alignment metrics)
    _METRIC_LABELS = [
        ("spearman_rho", "rho"), ("pearson_r", "r"),
        ("peak_f1", "PeakF1"), ("dtw_sim", "DTW"),
        ("cross_corr", "XCorr"), ("grad_cosine", "GradCos"),
    ]
    if rank_info:
        parts = [f"{lbl}={rank_info[key]:.3f}"
                 for key, lbl in _METRIC_LABELS if key in rank_info]
        if parts:
            fig.text(0.98, 0.005, "  ".join(parts),
                     ha="right", va="bottom", fontsize=6.5,
                     fontstyle="italic", color="#555555")

    fig.align_ylabels(axes)
    fig.savefig(out_path)
    plt.close(fig)
    print(f"Saved  {out_path}")


# ── main ─────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="Plot score curves for top-N or specific videos")
    parser.add_argument("--top", type=int, default=5,
                        help="Number of top videos per dataset (default: 5)")
    parser.add_argument("--video", action="append", default=[],
                        help="Specific video as dataset:name (e.g. summe:Air_Force_One)")
    args = parser.parse_args()

    if args.video:
        # plot specific videos
        for spec in args.video:
            ds, vname = spec.split(":", 1)
            out = os.path.join(OUT_DIR, f"score_curve_{ds}_{vname}.pdf")
            plot_video(ds, vname, out)
    else:
        # batch: top-N per dataset
        rankings = load_rankings()
        for ds in ["summe", "tvsum"]:
            top_videos = rankings[ds][:args.top]
            for rank, entry in enumerate(top_videos, 1):
                vname = entry["video_name"]
                out = os.path.join(
                    OUT_DIR, f"score_curve_{ds}_top{rank}_{vname}.pdf")
                plot_video(ds, vname, out, rank_info=entry)


if __name__ == "__main__":
    main()
