# 帧字幕生成配置
model_path: "Salesforce/blip-image-captioning-base"
device: "cuda"
model_name: "blip"
# frame_caption_save_dir: "/root/tfnet/data/captions/frame_caption/blip/"

# # 帧字幕生成配置
# pretrained: "lmms-lab/LLaVA-Video-7B-Qwen2"
# model_base: null
# model_name: "blip"
# device: "cuda"
# device_map: "auto"
# conv_template: "qwen_1_5"
# torch_dtype: "float16"
# max_new_tokens: 4096

# frame_caption_prompt: "Please describe this image in details."